Add UUID generator
public-apis/public-apis pull request #1140
Opened 2019-12-30 04:40 UTC by aarreedd

Added link to [uuidtools.com/docs](https://www.uuidtools.com/docs). Open source project provides API to generate UUIDs. Supports multiple UUID versions, bulk UUID generation, and UUID decoding. 

---

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-03-27 18:34 UTC, matheusfelipeog requested changes
Thanks for contribution @aarreedd 😄

2021-03-27 18:34 UTC, matheusfelipeog commented on README.md
> +| [UUID Generator](https://www.uuidtools.com/docs) | Generate UUIDs | No | Yes | No |
The `uuidtools.com/docs` uses cloudflare service, this broken our tests.

The solution I see to solve this without having to change anything in your project is to add the repository link on github.

Can you do that, please?

```suggestion
| [UUID Generator](https://github.com/aarreedd/uuidtools.com) | Generate UUIDs | No | Yes | No |
```

2021-03-28 12:19 UTC, aarreedd commented
I've changed the cloudflare settings. I think the test will pass now.

2021-03-29 00:48 UTC, matheusfelipeog commented
Oh, right. Thanks for the change ;)

2021-03-29 00:49 UTC, matheusfelipeog approved these changes

2021-03-29 00:50 UTC, merged