Updated Readme to add entry for google dictionary API.
public-apis/public-apis pull request #1165
Opened 2020-02-18 04:31 UTC by meetDeveloper

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2020-02-18 04:32 UTC, meetDeveloper commented
Also the dictionary entry I added is open source, source code can be found here https://github.com/meetDeveloper/googleDictionaryAPI.

2021-03-30 00:54 UTC, matheusfelipeog requested changes
Thanks for contribution @meetDeveloper 😄

2021-03-30 00:54 UTC, matheusfelipeog commented on README.md
> +| [Google Dictionary API](https://dictionaryapi.dev) | Word definitions, examples, pronunciations, synonyms, and others | No | Yes | Yes |
Can you change the title `Google Dictionary API` to `Google Dictionary`, please?

```suggestion
| [Google Dictionary](https://dictionaryapi.dev) | Word definitions, examples, pronunciations, synonyms, and others | No | Yes | Yes |
```

Title should not end with "... API". Every entry is an API here! 😅

2021-04-27 10:01 UTC, marekdano commented
@meetDeveloper can you please check the suggestion from @matheusfelipeog and update your record accordingly?

2021-08-09 09:05 UTC, ElWeroRanchero commented
Git//ElWeroRanchero

2021-08-09 10:34 UTC, meetDeveloper commented
@ElWeroRanchero  This has already been added, closing this PR.

2021-08-09 10:34 UTC, closed without merging