Added Open Disease APÌ
public-apis/public-apis pull request #1342
Opened 2020-08-18 14:15 UTC by puf17640

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-04-27 03:46 UTC, matheusfelipeog requested changes
Thanks for your contribution @puf17640 😄 

Can you resolve this review, please?

2021-04-27 03:46 UTC, matheusfelipeog commented on README.md
> +| [Open Disease API](https://disease.sh/) | API for Current cases and more stuff about COVID-19 and Influenza | No | Yes | Yes |
Remove the `API` string of title:

```suggestion
| [Open Disease](https://disease.sh/) | API for Current cases and more stuff about COVID-19 and Influenza | No | Yes | Yes |
```
All entries are already an API.

2021-05-06 14:07 UTC, puf17640 commented
Actually didn't even know this PR was still open haha but it should be fixed now! 👍🏻  Thanks!

2021-05-08 05:42 UTC, matheusfelipeog approved these changes
Now everything is correct 😆 

Thanks!

2021-05-08 05:44 UTC, merged