Added UK Government coronavirus API
public-apis/public-apis pull request #1344
Opened 2020-08-19 13:38 UTC by brychanthomas

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] Your additions are ordered alphabetically
- [x] Your submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column should be padded with one space on either side
- [x] You have searched the repository for any relevant issues or pull requests
- [x] Any category you are creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2020-10-22 15:42 UTC, 53jk1 approved these changes

2021-04-10 19:42 UTC, marekdano commented
Thanks for the contribution @brychanthomas!
Can you please resolve the conflict?

2021-04-11 17:11 UTC, brychanthomas commented
I have resolved the conflict, but the checks are failing because [the link](https://coronavirus.data.gov.uk/developers-guide) returns a 404 status. However, the link still works - I assume there is a bug with the government's website.

2021-04-12 14:01 UTC, marekdano commented
Thanks for resolving the conflict @brychanthomas!

Can I ask you to replace your link `https://coronavirus.data.gov.uk/developers-guide` with `https://coronavirus.data.gov.uk/details/developers-guide`? I can see that the link is redirected.
And the best is also to [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) all your commits.

2021-04-12 14:20 UTC, marekdano requested changes
Thanks for resolving the conflict @brychanthomas!
I left a comment.

Can I ask you also to squash all your commits?

2021-04-12 14:20 UTC, marekdano commented on README.md
> +| [Coronavirus in the UK](https://coronavirus.data.gov.uk/developers-guide) | UK Government coronavirus data, including deaths and cases by region | No | Yes | Unknown |
Can I ask you to replace your link https://coronavirus.data.gov.uk/developers-guide with https://coronavirus.data.gov.uk/details/developers-guide? I can see that the link is redirected.

2021-04-12 19:22 UTC, brychanthomas commented
Ah, I didn't notice the redirect! I have fixed the link and squashed it to one commit.

2021-04-13 09:13 UTC, marekdano approved these changes

2021-04-13 09:14 UTC, merged