add apis in books genre
public-apis/public-apis pull request #1388
Opened 2020-10-01 10:35 UTC by heygroot

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] Your additions are ordered alphabetically
- [ ] Your submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column should be padded with one space on either side
- [ ] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2020-10-11 13:09 UTC, yannbertrand requested changes
Please update your APIs descriptions to explain what's in each one.

2020-10-11 13:09 UTC, yannbertrand commented on README.md
> +| [The Bible](https://scripture.api.bible/) | Books | `apiKey` | Yes | Unknown |
```suggestion
| [The Bible](https://docs.api.bible) | Books | `apiKey` | Yes | Unknown |
```

2021-08-16 03:13 UTC, amiskus999 commented
Hello 
Please I'm a new python programmer with skills in python data structures, please can I get projects to work on?

2021-09-14 23:13 UTC, closed without merging

2021-09-14 23:16 UTC, matheusfelipeog commented
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002