Adds Education Section and College Score Card API
public-apis/public-apis pull request #1405
Opened 2020-10-07 22:10 UTC by saykaren

Thank you for taking the time to work on a Pull Request for this project!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] Your additions are ordered alphabetically
- [ ] Your submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column should be padded with one space on either side
- [ ] You have searched the repository for any relevant issues or pull requests
- [ ] Any category you are creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-04-28 17:17 UTC, marekdano commented on README.md
> +| [CollegeScoreCard.ed.gov](https://api.data.gov/ed/collegescorecard/v1/schools) | College Score Card | Yes | Yes | Unknown |
This fits better for the `Open Data` section. Can you please move it there?

Creating a new section requires having a least 3 records there.

2021-04-28 17:18 UTC, marekdano requested changes
Thanks for the contribution @saykaren!
Can you please review the requested change?

2021-10-02 22:41 UTC, leahfern commented
This API has already been added to the list separately.

2021-10-05 04:16 UTC, closed without merging

2021-10-05 04:17 UTC, matheusfelipeog commented
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002