Another new api
public-apis/public-apis pull request #1412
Opened 2020-10-11 13:08 UTC by 0xBenjaminTaylor

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2020-10-11 16:32 UTC, yannbertrand requested changes

2020-10-11 16:32 UTC, yannbertrand commented on README.md
> +| [Intelligence X](https://github.com/IntelligenceX/SDK) | Perform OSINT via Intelligence X | `apiKey` | Yes | Unknown |
```suggestion
| [Intelligence X](https://github.com/IntelligenceX/SDK/blob/master/Intelligence%20X%20API.pdf) | Perform OSINT via Intelligence X | `apiKey` | Yes | Unknown |
```

2020-10-11 21:09 UTC, nishant-ranjan28 approved these changes

2020-10-22 15:38 UTC, 53jk1 approved these changes

2020-10-25 16:44 UTC, merged

2020-10-25 16:44 UTC, yannbertrand commented
Thanks