Added troposphere.io weather API
public-apis/public-apis pull request #1444
Opened 2020-11-01 14:51 UTC by ManuelBauer

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-02-09 21:13 UTC, ManuelBauer commented
Any updates on the pull request status? Would be nice to be a part of this list :)

2021-04-04 05:48 UTC, PawelBorkar requested changes
Please do the change stated below and also resolve the conflict.

2021-04-04 05:48 UTC, PawelBorkar commented on README.md
> +| [Troposphere.io](https://www.troposphere.io/developer) | Global weather and climate data | `apiKey` | Yes | Yes |
```suggestion
| [Troposphere](https://www.troposphere.io/developer) | Global weather and climate data | `apiKey` | Yes | Yes |
```

2021-04-04 05:48 UTC, PawelBorkar commented on README.md
> +| [Troposphere.io](https://www.troposphere.io/developer) | Global weather and climate data | `apiKey` | Yes | Yes |
No need to add the TLD as it was already there in the [URL](https://www.troposphere.io/developer)

2021-04-19 19:06 UTC, ManuelBauer commented
@PawelBorkar I've fixed the issue with the TLD and resolved the conflict :)

2021-04-20 04:07 UTC, PawelBorkar commented
Thanks @ManuelBauer!
Can you please squash the commits into a single one?

Otherwise you can also make a new PR and ref. this whatever seems comfortable to you.

2021-04-20 05:28 UTC, ManuelBauer commented
@PawelBorkar I've squashed all commits into a single one 👍

2021-04-20 11:50 UTC, PawelBorkar commented
Thanks for your contribution @ManuelBauer ☺️

2021-04-20 11:50 UTC, merged