ISS satellite location
public-apis/public-apis pull request #1453
Opened 2020-11-12 22:51 UTC by Luke-Herring

| [ISS satellite](https://api.wheretheiss.at/v1/satellites/25544) | Shows location of ISS satellite | No | Yes | Yes |

2021-01-11 16:16 UTC, GeorgeWL commented
You seem to have ignored the https://github.com/public-apis/public-apis/blob/5a3903216f61708bd92cbd21297a4822783269bf/.github/CONTRIBUTING.md which tells you to squash into a single commit

2021-02-25 21:29 UTC, GeorgeWL requested changes
You seem to have ignored the https://github.com/public-apis/public-apis/blob/5a3903216f61708bd92cbd21297a4822783269bf/.github/CONTRIBUTING.md which tells you to squash into a single commit

2021-03-20 23:30 UTC, GeorgeWL requested changes
what has this to do with this pull request?

Branch it and make anew request

2021-03-28 02:32 UTC, Valter29 approved these changes

2021-03-29 13:24 UTC, YaroYaro168 approved these changes

2021-05-01 05:26 UTC, closed without merging