CoinRanking Auth
public-apis/public-apis pull request #1540
Opened 2021-01-29 00:17 UTC by tannershimanek

Updated the authentication for CoinRanking from "No" to "apiKey.

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-01-29 00:21 UTC, tannershimanek commented
Just a small change, but increasing accuracy

2021-04-18 07:57 UTC, marekdano requested changes
Thanks for the contribution @tannershimanek!
Can you please resolve the conflict?

2021-04-18 07:57 UTC, marekdano commented on README.md
> +| [CoinRanking](https://docs.coinranking.com/) | Live Cryptocurrency data | `apiKey` | Yes | Unknown |
When you resolve the conflict please make sure the current url of `https://developers.coinranking.com/api/documentation/` is listed, please.

2021-05-21 17:19 UTC, pawelbr commented
@tannershimanek 
Don't forget to squash all the commits into the single one after committing the changes suggested by @marekdano

2021-10-03 03:52 UTC, closed without merging

2021-10-03 03:53 UTC, matheusfelipeog commented
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002