Update README.md
public-apis/public-apis pull request #1616
Opened 2021-04-06 09:27 UTC by JulHelm

Hi. Our german Bahn changet the URI to their APIs. Cheers. Julian

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-04-21 17:17 UTC, catcosmicice approved these changes

2021-04-25 08:53 UTC, marekdano requested changes
Thanks for the contribution @JulHelm!
My comment is below.

2021-04-25 08:53 UTC, marekdano commented on README.md
> +| [Transport for Germany](https://developer.deutschebahn.com/store/apis/list) | Deutsche Bahn (DB) API | `apiKey` | No | Unknown |
`No` should be `Yes` since API is `https`. Can you please update it?

2021-05-21 12:37 UTC, pawelbr commented
@JulHelm 
Can you commit the changes that @marekdano has suggested

2021-10-03 18:55 UTC, hjwk commented
is the new address really correct ? It is impossible to access it, 
Should it perhaps be this one instead ? 
https://data.deutschebahn.com/dataset.groups.apis.html

Or perhaps simply keep the old one ? It is still accessible

2021-10-05 04:58 UTC, matheusfelipeog commented
> is the new address really correct ? I know it might auth to access but the answer I get is weird :
> ...
> The old adress is still accessible

@hjwk You're right. This new link is broken, I will keep the current one.

Thanks for letting us know ;)

2021-10-05 04:58 UTC, closed without merging