Added static site for the public-apis.dev domain
public-apis/public-apis pull request #1633
Opened 2021-04-13 17:34 UTC by PawelBorkar

With reference to #1612 this PR will add a static site for the public-apis with url public-apis.dev
As we all know we have to use GitHub Pages while deploying the site to the mentioned domain after this PR got merged.
But while doing so there's one problem we are unable to enforce the Https in for our domain as some the APIs are not having https in their domain which means their lacking the SSL certification which makes our site to fall in the category of [mixed content](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https).

Here are the screenshots of the website built by using [MKDocs](https://mkdocs.org)

![Public-Apis_homepage](https://user-images.githubusercontent.com/36134699/114595685-491edf00-9cac-11eb-9f5f-047f5b73b720.png)

![Public-Apis_search](https://user-images.githubusercontent.com/36134699/114595753-5a67eb80-9cac-11eb-8d0b-0f314d491aae.png)

![Public-Apis_contributepage](https://user-images.githubusercontent.com/36134699/114595803-66ec4400-9cac-11eb-97b1-ac5c32101249.png)

![Public-Apis_License](https://user-images.githubusercontent.com/36134699/114595861-7a97aa80-9cac-11eb-838b-b85ff485b6b9.png)

2021-04-13 20:16 UTC, zaherg commented
@PawelBorkar  we can test it and if the mixed content caused any issue I can use cloudflare (instead of google) as the DNS management and enforce https using them.

2021-04-13 21:15 UTC, zaherg commented
I have setup the required DNS modifications so once you enable/merged this PR the domain should work with no time.

2021-04-14 09:36 UTC, sent requested changes
Don't use a user-provided domain names, there is no guarantee that they just could disappear anytime.

Github.io is the way to go.

2021-04-14 09:36 UTC, sent commented on mkdocs.yml
> +site_url: https://public-apis.dev
```suggestion
site_url: http://public-apis.github.io/
```

2021-04-16 21:12 UTC, matheusfelipeog reviewed
Good job @PawelBorkar 😄

But with this file structure we will have to keep the `README.md` file and `docs/index.html` synchronized manually with each new api added. This is repeated for the other files too: `contributions.md`, `license`

I think it is better to use just 1 file to list the APIs and be used as a basis for the site. This is good for us who maintain the project and for the employees. So we avoid duplicate work.

The MKDocs does not allow using the root of the directory. It needs a child directory to structure its files, for example, a `docs` directory. Sorry for indicating MKDocs for this, I didn't know. 😢 

I looked for alternatives to solve this problem and found [Docsify](https://docsify.js.org/) ([Docsify on Github](https://github.com/docsifyjs/docsify))

The [free-for-dev](https://github.com/ripienaar/free-for-dev) project uses it, you can see how it looks here: [https://free-for.dev](https://free-for.dev/#/)

And everything seems to work well.

I did some tests to see it working:

![image](https://user-images.githubusercontent.com/50463866/115083481-cd0bdd80-9edd-11eb-8ed2-a23d2de301d7.png)
![image](https://user-images.githubusercontent.com/50463866/115083512-d85f0900-9edd-11eb-9a0d-03eae0a21dce.png)

I just had to make a correction to the `README.md` file to work.

What do you think?

If you like it and allow it, I can do that job.

And again, sorry.

2021-04-17 07:37 UTC, marekdano commented
@PawelBorkar Thank you very much for working on putting the project on the website version. I appreciate it!!!

> But with this file structure we will have to keep the README.md file and docs/index.html synchronized manually with each new api added. This is repeated for the other files too: contributions.md

@matheusfelipeog I agree that it'll be duplicate work. But this can be done by having a script that will update the `docs` folder every time before deploying the site.

TBH I'm happy with both options, using MKDocs (doing all manual updates by a script) or Docsify. We should decide what'll involve less maintenance to update the doc.

2021-04-17 07:39 UTC, marekdano reviewed
@PawelBorkar Thank you very much for working on putting the project on the website version. I appreciate it!!!

But with this file structure we will have to keep the README.md file and docs/index.html synchronized manually with each new api added. This is repeated for the other files too: contributions.md

@matheusfelipeog I agree that it'll be duplicate work. But this can be done by having a script that will update the docs folder every time before deploying the site.

TBH I'm happy with both options, using MKDocs (doing all manual updates by a script) or Docsify. We should decide what'll involve less maintenance to update the doc.

2021-04-17 12:50 UTC, PawelBorkar commented
Thanks for the feedback @matheusfelipeog and for pointing out the limitations of MKDocs and for finding the alternative to it. 
When I was testing the site I do get to know that we have to update the docs/index.md as well whenever we update the README but at that time I thought that we'll write a script that will automate this as @marekdano has [suggested ](https://github.com/public-apis/public-apis/pull/1633#pullrequestreview-638207050) in this way we don't have to bother about the docs/index.md

> The free-for-dev project uses it, you can see how it looks here: https://free-for.dev
> And everything seems to work well

I did check out their website and found some limitations.

- In order to render the README we have to remove all the badges from the README otherwise they too get rendered.
- The search functionality makes it difficult for the reader to read as it gets out of focus from the reader's eyes.


As you can see here

![Screenshot (57)](https://user-images.githubusercontent.com/36134699/115113287-360b5800-9fa7-11eb-9084-6d848aa162ee.png)

As Compared to 

![search](https://user-images.githubusercontent.com/36134699/114595753-5a67eb80-9cac-11eb-8d0b-0f314d491aae.png)

And above all, we need to make the site easy to navigate for the new users/contributors which will increase their user experience and pool in more contributors which can be achieved here as it gives us a navigation bar with all the necessary functionality and search. It's easy to see the contributing guide and license in here as compared to what we are getting with Docsify.

![Navigate](https://user-images.githubusercontent.com/36134699/114595803-66ec4400-9cac-11eb-97b1-ac5c32101249.png)

We just need to add a script will which pull the changes made in README & Contributing.md and copy it to the docs/index.md and contributing.md.

Feel free to give your suggestions.

Thanks You All :-)

2021-07-08 17:03 UTC, Tiaogaviao approved these changes
Ganhar dinheiro baixando o Kwai!https://s.kwai.app/s/oenFdtwS

2021-07-08 17:04 UTC, Tiaogaviao commented
Ganhar dinheiro baixando o Kwai!https://s.kwai.app/s/oenFdtwS

2021-11-24 08:18 UTC, pawelborkar commented
Closing this as there are many unofficial and better alternative available now.

2021-11-24 08:18 UTC, closed without merging