Add Glitterly
public-apis/public-apis pull request #1640
Opened 2021-04-14 15:09 UTC by OskarAhl

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-05-14 15:27 UTC, marekdano requested changes
Thanks for the contribution @OskarAhl!

Can you please update the url?

2021-05-14 15:27 UTC, marekdano commented on README.md
> +| [Glitterly](https://glitterly.app/) | Image generation API | `apiKey` | Yes | Yes |
```suggestion
| [Glitterly](https://developers.glitterly.app) | Image generation API | `apiKey` | Yes | Yes |
```
The link goes straight to the API doc.

2021-05-15 02:42 UTC, OskarAhl commented
> Thanks for the contribution @OskarAhl!
> 
> Can you please update the url?

@marekdano thanks for the comment, updated it

2021-05-15 07:21 UTC, marekdano approved these changes

2021-05-15 07:21 UTC, merged