add autochess vng api
public-apis/public-apis pull request #1679
Opened 2021-04-29 14:14 UTC by didadadida93

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
-  @[x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-04-29 14:26 UTC, marekdano commented
ref #1620

2021-04-29 14:34 UTC, marekdano requested changes
Thanks for opening the PR @didadadida93!
Can you please update your record?

2021-04-29 14:34 UTC, marekdano commented on README.md
> +| [Autochess VNG API](https://github.com/didadadida93/autochess-vng-api) | Rest Api for Autochess VNG | No | Yes | Yes |
The validation format check felt here: 
<img width="1399" alt="Screenshot 2021-04-29 at 15 30 29" src="https://user-images.githubusercontent.com/1914165/116568100-1dccfe80-a900-11eb-90a9-fbad885034de.png">

Can you please remove `API` from the title?

2021-04-30 04:01 UTC, didadadida93 commented
> Thanks for opening the PR @didadadida93!
> Can you please update your record?

done :+1:

2021-04-30 07:13 UTC, marekdano approved these changes

2021-04-30 07:13 UTC, merged