Add Shrtcode API
public-apis/public-apis pull request #1701
Opened 2021-05-05 21:43 UTC by AnTheMaker

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-05-06 13:41 UTC, schmelto approved these changes

2021-05-06 19:59 UTC, gerslun approved these changes

2021-05-06 22:33 UTC, lodenrogue approved these changes

2021-05-19 08:42 UTC, pawelbr requested changes
Thanks for the contribution @AnTheMaker
Please commit the changes requested.

2021-05-19 08:42 UTC, pawelbr commented on README.md
> +| [Shrtcode](https://shrtco.de/docs) | URl Shortener with multiple Domains, No signup | No | Yes | Yes |
```suggestion
| [Shrtcode](https://shrtco.de/docs) | URl Shortener with multiple Domains | No | Yes | Yes |
```

2021-05-20 11:13 UTC, schmelto approved these changes

2021-05-20 18:13 UTC, pawelbr approved these changes

2021-05-20 18:16 UTC, merged