Add URLHaus API
public-apis/public-apis pull request #1712
Opened 2021-05-09 09:56 UTC by FH089

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-05-20 23:21 UTC, matheusfelipeog requested changes
Thanks for your contribution @FH089 ✋ 

The API is Ok. Only the markdown format is organized incorrectly.

Can you solve this review, please?

2021-05-20 23:21 UTC, matheusfelipeog commented on README.md
> +| [URLhaus](https://urlhaus-api.abuse.ch/)| Bulk queries and Download Malware Samples| No | Yes | Unknown|
Each segment must start and end with exactly 1 space.

```suggestion
| [URLhaus](https://urlhaus-api.abuse.ch/) | Bulk queries and Download Malware Samples | No | Yes | Unknown |
```

Can you fix this, please?

2021-05-22 19:10 UTC, matheusfelipeog approved these changes
Thanks @FH089 😄

2021-05-22 19:10 UTC, merged

2021-05-22 19:18 UTC, FH089 commented
your welcome @matheusfelipeog  :+1: