added my free quote API to the list
public-apis/public-apis pull request #1722
Opened 2021-05-15 18:56 UTC by F4R4N

- [x ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ x] My addition is ordered alphabetically
- [ x] My submission has a useful description
- [ x] The description does not end with punctuation
- [ x] Each table column is padded with one space on either side
- [ x] I have searched the repository for any relevant issues or pull requests
- [ x] Any category I am creating has the minimum requirement of 3 items
- [ x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-05-21 12:32 UTC, pawelbr commented
Is there any documentation of it?

2021-05-21 19:41 UTC, matheusfelipeog commented
> Is there any documentation of it?
> 
> I don't find any.

I found here: https://github.com/F4R4N/movie-quote

2021-05-22 05:40 UTC, pawelbr commented
@F4R4N 
It's better to add the URL of the documentation rather than adding the URL of the site itself.

2021-05-22 05:44 UTC, pawelbr requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-05-22 05:44 UTC, pawelbr commented on README.md
> +| [Movie Quotes](https://movie-quote-api.herokuapp.com/v1/quote/) | Random Movie and Series Quotes | No | Yes | No |
```suggestion
| [Movie Quotes](https://github.com/F4R4N/movie-quote) | Random Movie and Series Quotes | No | Yes | No |
```

2021-05-22 07:19 UTC, F4R4N commented
sorry I don't know how to squash on the pull request. I squashed the commits in my forked master branch. please guide me through it.

2021-05-22 09:43 UTC, pawelbr commented
use `git push --force` command

2021-05-22 13:59 UTC, F4R4N commented
ok, thanks

2021-05-22 13:59 UTC, closed without merging