CORS support mentioned and URL updated
public-apis/public-apis pull request #1727
Opened 2021-05-20 05:16 UTC by ipapi-co

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

2021-05-20 18:23 UTC, pawelbr requested changes
Thanks for the contribution @ipapi-co 
But the previous link is fine no need to change it.
Please commit the suggestions stated below and don't forget to squash it.

2021-05-20 18:23 UTC, pawelbr commented on README.md
> +| [IP Location](https://ipapi.co/) | Find IP address location information | No | Yes | Yes |
```suggestion
| [IP Location](https://ipapi.co/api#introduction) | Find IP address location information | No | Yes | Yes |
```

2021-05-21 06:10 UTC, ipapi-co commented
Getting an error with squash. We will close this PR & re-submit with the suggested changes. Thank you for your help.

2021-05-21 06:10 UTC, closed without merging

2021-05-21 11:43 UTC, pawelbr commented
Sure @ipapi-co 

You're welcome ☺️