Edit football-data API
public-apis/public-apis pull request #1745
Opened 2021-05-27 02:25 UTC by WiLLiaM-noD

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-05-27 17:33 UTC, pawelborkar requested changes
Thanks for opening this PR @WiLLiaM-noD 
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-05-27 17:33 UTC, pawelborkar commented on README.md
> +| [Football-Data.org](http://api.football-data.org/index) | Football Data with match info, player, team, and competitions | `X-Mashape-Key` | Yes | Unknown |
/

2021-05-27 17:33 UTC, pawelborkar commented on README.md
> +| [Football-Data.org](http://api.football-data.org/index) | Football Data with match info, player, team, and competitions | `X-Mashape-Key` | Yes | Unknown |
No need to add the TLD ref. [contribution guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md)

2021-05-27 17:37 UTC, pawelborkar requested changes

2021-05-27 17:37 UTC, pawelborkar commented on README.md
> +| [Football-Data.org](http://api.football-data.org/index) | Football Data with match info, player, team, and competitions | `X-Mashape-Key` | Yes | Unknown |
```suggestion
| [Football-Data](http://api.football-data.org/index) | Football Data with match info, player, team, and competitions | `X-Mashape-Key` | Yes | Unknown |
```

2021-05-27 17:37 UTC, pawelborkar commented on README.md
> +| [Football-Data.org](http://api.football-data.org/index) | Football Data with match info, player, team, and competitions | `X-Mashape-Key` | Yes | Unknown |
No need to add the TLD ref [contribution.md](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md)

2021-06-01 07:28 UTC, WiLLiaM-noD commented
I've already changed the API name.

2021-06-01 17:07 UTC, pawelborkar commented
Please squash all the commits into a single one. @WiLLiaM-noD

2021-06-03 10:17 UTC, WiLLiaM-noD commented
Finished squash all the commit

2021-06-16 06:08 UTC, pawelborkar commented
The commits are not squashed as you can see in the commit tab of this PR.
I would encourage you to make a new PR with the suggested changes and don't forget to mention this PR in the new one.

Thanks.

2021-08-15 12:35 UTC, pawelborkar commented
Hi @william-nod ,
Please update the PR with the suggestions stated above.

2021-09-05 01:39 UTC, closed without merging