Add Datamuse API
public-apis/public-apis pull request #1756
Opened 2021-06-03 21:56 UTC by andrealps

Add Datamuse API to Open Source Projects

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-06-03 23:56 UTC, matheusfelipeog requested changes
Thanks for your contribution @andrealps 😄 

Can you resolve this review, please?

2021-06-03 23:56 UTC, matheusfelipeog commented on README.md
> +| [Datamuse](http://www.datamuse.com/api/) | Word-finding query engine | No | Yes | Unknown |
If this API supports HTTPS, use this link here.

```suggestion
| [Datamuse](https://www.datamuse.com/api/) | Word-finding query engine | No | Yes | Unknown |
```

2021-06-04 13:54 UTC, andrealps commented
Sorry, now it's fixed 😄

2021-06-04 14:03 UTC, matheusfelipeog approved these changes
A big THANKS for your update @andrealps 😄

2021-06-04 14:04 UTC, merged