add EscapeAPI to security
public-apis/public-apis pull request #1760
Opened 2021-06-04 15:10 UTC by polarspetroll

- [X] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [X] My addition is ordered alphabetically
- [X] My submission has a useful description
- [X] The description does not end with punctuation
- [X] Each table column is padded with one space on either side
- [X] I have searched the repository for any relevant issues or pull requests
- [X] Any category I am creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

2021-06-09 05:04 UTC, matheusfelipeog requested changes
Thanks for your contribution @polarspetroll ✋ 

Can you resolve the review, please?

2021-06-09 05:04 UTC, matheusfelipeog commented on README.md
> +| [Escape](https://github.com/polarspetroll/EscapeAPI)| an API for escaping different kind of queries | No | Yes | No
- Put a blank space between the link and `|` character
- Start the description with a capital letter
- And at the end of the line put a `|`

```suggestion
| [Escape](https://github.com/polarspetroll/EscapeAPI) | An API for escaping different kind of queries | No | Yes | No |
```

2021-06-09 08:17 UTC, polarspetroll commented
Hi, Thanks for your reply . Changes committed successfully

2021-06-10 02:25 UTC, matheusfelipeog approved these changes
Perfect ❤️ 

A big THANKS, we are grateful for your update.

2021-06-10 02:26 UTC, merged