Update README.md
public-apis/public-apis pull request #1765
Opened 2021-06-05 19:12 UTC by jaredcassoutt

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-06-05 19:13 UTC, jaredcassoutt commented
Added the Styvio API to the Finance section of the repository's README.md file

2021-06-10 04:58 UTC, matheusfelipeog requested changes
Thanks for your contribution, we are grateful for that. 😄 

Can you resolve the review, please?

2021-06-10 04:58 UTC, matheusfelipeog commented on README.md
> +| [Styvio](https://www.Styvio.com) | Realtime and historical stock data and current stock sentiment | No | No | Unknown |
This API support HTTPS protocol

```suggestion
| [Styvio](https://www.Styvio.com) | Realtime and historical stock data and current stock sentiment | No | Yes | Unknown |
```

2021-06-12 01:03 UTC, matheusfelipeog approved these changes
Thanks for your update @jaredcassoutt, we are grateful for that ❤️

2021-06-12 01:04 UTC, merged

2021-09-02 13:11 UTC, matias904 approved these changes

2021-09-02 22:35 UTC, matias904 approved these changes