Update README.md
public-apis/public-apis pull request #1790
Opened 2021-06-14 07:54 UTC by ivanstan

- [ ] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-06-16 06:12 UTC, pawelborkar requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-06-16 06:12 UTC, pawelborkar commented on README.md
> +| [TLE API](https://tle.ivanstanojevic.me/#/docs) | Satellite information | No | Yes | Unknown |
```suggestion
| [TLE](https://tle.ivanstanojevic.me/#/docs) | Satellite information | No | Yes | Unknown |
```

2021-06-16 06:12 UTC, pawelborkar commented on README.md
> +| [TLE API](https://tle.ivanstanojevic.me/#/docs) | Satellite information | No | Yes | Unknown |
No need to add API in the name .

2021-09-02 22:32 UTC, matias904 approved these changes

2021-10-05 05:26 UTC, closed without merging

2021-10-05 05:26 UTC, matheusfelipeog commented
This PR is inactive, so the API was added in another PR/commit.

More information at: #2002