Add OpenSky Network API to Transportation
public-apis/public-apis pull request #1796
Opened 2021-06-18 16:06 UTC by arthurlli

- [-] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [-] My addition is ordered alphabetically
- [-] My submission has a useful description
- [-] The description does not end with punctuation
- [-] Each table column is padded with one space on either side
- [-] I have searched the repository for any relevant issues or pull requests
- [-] Any category I am creating has the minimum requirement of 3 items
- [-] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-06-19 11:32 UTC, arthurlli commented
I found url for Salesfly PDF API is invalid, so I modified and attached another link, which is squashed with my previous commit. Hopes this helps.

2021-06-23 01:31 UTC, matheusfelipeog requested changes
Hi @arthurlli ✋ 

Thanks for your contribution, we are grateful for that ❤️ 

Can you resolve the review, please?

2021-06-23 01:31 UTC, matheusfelipeog commented on README.md
> +| [Salesfly PDF](https://developers.salesfly.com/swift/) | HTML/URL to PDF | `apiKey` | Yes | Yes |
This API is in private beta.


![image](https://user-images.githubusercontent.com/50463866/123019699-5e4c7400-d3a7-11eb-8e64-981521bf9978.png)

Can you remove, please?

```suggestion
```

2021-06-23 04:45 UTC, arthurlli commented
Hi @matheusfelipeog, thank you for the review, I have updated and squashed the commits, please check. Thanks!:smile:

2021-06-23 04:54 UTC, arthurlli commented
> 
> 
> Hi @matheusfelipeog, thank you for the review, I have updated and squashed the commits, please check. Thanks!😄

I just noticed that I "force-push" the commit, sorry if it may cause some issue.

2021-06-23 13:04 UTC, matheusfelipeog approved these changes
Perfect ❤️

2021-06-23 13:06 UTC, matheusfelipeog commented
> I just noticed that I "force-push" the commit, sorry if it may cause some issue.

No problem, you did the right. 😆

2021-06-23 13:07 UTC, merged

2021-06-23 13:38 UTC, arthurlli commented
Great! Thank you!

2021-09-02 13:09 UTC, matias904 requested changes
- [ ]