Added Axolotl API
public-apis/public-apis pull request #1841
Opened 2021-07-10 19:40 UTC by AceKiron

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-07-11 07:02 UTC, adamsofea1111 approved these changes

2021-07-11 12:34 UTC, fintzd approved these changes
LGTM I guess

2021-07-14 07:39 UTC, AceKiron commented
.... How long do these PRs usually take?

2021-07-14 08:02 UTC, fintzd commented
Good question, but I do not know unfortunately!

2021-07-18 11:11 UTC, adamsofea1111 approved these changes

2021-07-19 07:36 UTC, marekdano requested changes
Thanks for the contribution @AceKiron!

Please check my suggestion above.

2021-07-19 07:36 UTC, marekdano commented on README.md
> +| [Axolotl API](https://theaxolotlapi.netlify.app/) | Collection of axolotl pictures and facts | No | Yes | Unkown
```suggestion
| [Axolotl](https://theaxolotlapi.netlify.app/) | Collection of axolotl pictures and facts | No | Yes | Unknown
```

`API` shouldn't be in the name

2021-07-19 14:10 UTC, AceKiron commented
Checked and updated it @marekdano

2021-07-19 14:13 UTC, AceKiron commented
Wait, now it isn't squashed anymore :/

2021-07-19 14:15 UTC, adamsofea1111 approved these changes

2021-07-19 14:16 UTC, adamsofea1111 approved these changes

2021-07-19 16:20 UTC, fintzd approved these changes
LGTM

2021-07-23 11:46 UTC, AceKiron commented
Hey, still waiting for this to hopefully get merged :/

2021-07-23 17:40 UTC, matheusfelipeog commented
Hi @AceKiron ✋ 

> Hey, still waiting for this to hopefully get merged :/

Sorry for the delay 😅

Can you [squashed](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) all changes into a single commit, please?

2021-07-23 18:01 UTC, AceKiron commented
> Can you [squashed](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) all changes into a single commit, please?

Sorry, but I just can't get squashing figured out, I'll close this PR and make a new one with a repo that actually has only 1 new commit.

2021-07-23 18:01 UTC, closed without merging

2021-07-23 18:04 UTC, AceKiron commented
@matheusfelipeog the new PR is #1886

2021-07-23 18:12 UTC, matheusfelipeog commented
Ok @AceKiron, I will review this now ;)