Added "Free Dictionary API" to Dictionaries
public-apis/public-apis pull request #1846
Opened 2021-07-14 19:25 UTC by Sanobelk

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-07-15 13:18 UTC, fintzd approved these changes
LGTM

2021-07-23 18:36 UTC, matheusfelipeog requested changes
Thanks for your contribution @Sanobelk :)

Can you resolve this review, please?

2021-07-23 18:36 UTC, matheusfelipeog commented on README.md
> +| [Free Dictionary API](https://dictionaryapi.dev/) | Definitions, phonetics, pronounciations, parts of speech, examples, synonyms | No | Yes | Unknown |
Title should not end with "... API". Every entry is an API here!

```suggestion
| [Free Dictionary](https://dictionaryapi.dev/) | Definitions, phonetics, pronounciations, parts of speech, examples, synonyms | No | Yes | Unknown |
```

2021-07-23 19:08 UTC, Sanobelk commented
> 
> 
> Thanks for your contribution @Sanobelk :)
> 
> Can you resolve this review, please?

Sure. I added the name because that's what the website specifically called it.

2021-07-23 20:00 UTC, matheusfelipeog approved these changes
Perfect. Thanks for updating it 😄

2021-07-23 20:01 UTC, merged