Add SeatGeek to Events section
public-apis/public-apis pull request #1851
Opened 2021-07-16 13:14 UTC by jeffrand

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-07-16 13:16 UTC, fintzd approved these changes
LGTM

2021-07-23 18:54 UTC, matheusfelipeog requested changes
Thanks for your contriibution @jeffrand 😄 

Can you resolve this review, please?

2021-07-23 18:54 UTC, matheusfelipeog commented on README.md
> +| [SeatGeek](https://platform.seatgeek.com/) | Search events, venues and performers | `apiKey` |  Yes  | Unknown |
Each segment must start and end with exactly 1 space

```suggestion
| [SeatGeek](https://platform.seatgeek.com/) | Search events, venues and performers | `apiKey` | Yes | Unknown |
```

2021-07-23 18:59 UTC, matheusfelipeog approved these changes
Wow, you were fast. We appreciate it, thank you very much.

2021-07-23 19:00 UTC, jeffrand commented
No problem!

2021-07-23 19:00 UTC, merged