Add TCGdex
public-apis/public-apis pull request #1875
Opened 2021-07-21 15:10 UTC by Aviortheking

- [x] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-07-21 16:32 UTC, pawelborkar requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-07-21 16:32 UTC, pawelborkar commented on README.md
> +| [TCGdex](https://www.tcgdex.net) | Multi languages Pokémon TCG Information | No | Yes | Yes |
```suggestion
| [TCGdex](https://www.tcgdex.net/docs) | Multi languages Pokémon TCG Information | No | Yes | Yes |
```

2021-07-22 07:44 UTC, Aviortheking commented on README.md
> +| [TCGdex](https://www.tcgdex.net) | Multi languages Pokémon TCG Information | No | Yes | Yes |
done

2021-07-22 08:04 UTC, pawelborkar approved these changes
Thanks for the contribution @Aviortheking

2021-07-22 08:05 UTC, merged