add: INEI from PERU
public-apis/public-apis pull request #1890
Opened 2021-07-24 03:58 UTC by romellfudi

- [X] My submission is formatted according to the guidelines in the [contributing guide](CONTRIBUTING.md)
- [X] My addition is ordered alphabetically
- [X] My submission has a useful description
- [X] The description does not end with punctuation
- [X] Each table column is padded with one space on either side
- [X] I have searched the repository for any relevant issues or pull requests
- [X] Any category I am creating has the minimum requirement of 3 items
- [X] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-07-30 05:50 UTC, matheusfelipeog requested changes
Thanks for your new contribution @romellfudi :)

Can you resolve this review, please?

2021-07-30 05:50 UTC, matheusfelipeog commented on README.md
> +| [INEI](http://iinei.inei.gob.pe/microdatos/) | Peruvian Statistical Government Open Data | No | Yes | Unknown |
This link does not support HTTPS protocol.

```suggestion
| [INEI](http://iinei.inei.gob.pe/microdatos/) | Peruvian Statistical Government Open Data | No | No | Unknown |
```

2021-07-30 06:38 UTC, romellfudi commented
I commit your correct suggestion

2021-07-30 08:00 UTC, pi-portharCommunity commented
I cannot resolve it. Are you a developer?

2021-07-30 11:53 UTC, cameron187187 commented
this is my account some is stealing my funds and on my account!! please help. other account is xan187 if i lose my account

2021-07-31 04:22 UTC, romellfudi commented
@matheusfelipeog It looks great, doesn't it?

2021-07-31 22:12 UTC, matheusfelipeog approved these changes
> Hello @matheusfelipeog It looks great, doesn't it?

@romellfudi That's perfect. A big THANK YOU for that. 😄

2021-07-31 22:13 UTC, merged