Add wttr API to Weather
public-apis/public-apis pull request #1913
Opened 2021-07-31 20:31 UTC by turn-a-round

- [* ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [* ] My addition is ordered alphabetically
- [* ] My submission has a useful description
- [ *] The description does not end with punctuation
- [* ] Each table column is padded with one space on either side
- [* ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ *] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-08-01 07:48 UTC, turn-a-round commented
Updated with new changes in the source.

2021-08-02 05:01 UTC, matheusfelipeog requested changes
Wow, this is nice 😄 

Thanks for your contribution @turn-a-round.

Can you resolve this review, please?

2021-08-02 05:03 UTC, matheusfelipeog commented
When finished, [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) all changes into a single commit, please 🙏

2021-08-02 05:56 UTC, turn-a-round commented on README.md
> +| [wttr](https://wttr.in) | :partly_sunny: The right way to check the weather [GitHub](https://github.com/chubin/wttr.in) | No | Yes | Unknown |
Done :+1:

2021-08-02 07:21 UTC, turn-a-round commented
> When finished, [squash](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) all changes into a single commit, please

Can't squash as I've merged with upsteam commits in between. Should I have to Close this PR & raise another?

2021-08-02 20:17 UTC, closed without merging