Add irisnet API
public-apis/public-apis pull request #1997
Opened 2021-08-27 07:57 UTC by tony-defa

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-08-29 08:00 UTC, pawelborkar requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-08-29 08:00 UTC, pawelborkar commented on README.md
> +| [irisnet](https://irisnet.de/api/) | Realtime content moderation API that blocks or blurs unwanted images in real-time | `apiKey` | Yes | Yes |
```suggestion
| [Irisnet](https://irisnet.de/api/) | Realtime content moderation API that blocks or blurs unwanted images in real-time | `apiKey` | Yes | Yes |
```

2021-09-02 22:28 UTC, matias904 approved these changes

2021-09-13 10:46 UTC, tony-defa commented
Suggestions have been commited and sqashed.

2021-09-14 06:27 UTC, pawelborkar approved these changes
Thanks for the contribution @tony-defa

2021-09-14 06:28 UTC, merged