Added `shortlink.api.fayas.me`
public-apis/public-apis pull request #2010
Opened 2021-09-01 06:05 UTC by FayasNoushad

`https://shortlink.api.fayas.me/?query=<sample-url>`

`https://shortlink.api.fayas.me/?query=https://github.com`

2021-09-01 06:29 UTC, matheusfelipeog requested changes
Thanks for your contribution @FayasNoushad 😄 

Can you resolve this review, please?

Also, don't forget to fix the alphabetical order.

2021-09-01 06:29 UTC, matheusfelipeog commented on README.md
> +| [All Shortener](https://shortlink.api.fayas.me) | Short URLs support so many domainsdomains | No | Yes | Unknown |
Use your project name in the title: Short Link.
Use a URL that goes to your project's documentation.
Fix API description.

```suggestion
| [Short Link](https://github.com/FayasNoushad/Short-Link-API) | Short URLs support so many domains | No | Yes | Unknown |
```

2021-09-01 06:37 UTC, matheusfelipeog commented
Now fix the alphabetical order so that I accept your API, please. ;)

2021-09-01 06:43 UTC, FayasNoushad commented
> Now fix the alphabetical order so that I accept your API, please. ;)

Done

2021-09-01 06:46 UTC, merged

2021-09-02 13:07 UTC, matias904 approved these changes

2021-09-02 13:08 UTC, FayasNoushad commented
> Now it's Ok. 
> 
> A big THANKS for your update @FayasNoushad ;)

Always welcome Mr. @matheusfelipeog