Added Geokeo geocoding API in alphabetical order
public-apis/public-apis pull request #2012
Opened 2021-09-01 08:10 UTC by thefool76

- [ ✔] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [✔ ] My addition is ordered alphabetically
- [✔ ] My submission has a useful description
- [ ✔] The description does not end with punctuation
- [✔ ] Each table column is padded with one space on either side
- [ ✔] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-09-01 08:10 UTC, thefool76 commented
Done!

2021-09-01 09:10 UTC, Loyoki approved these changes

2021-09-02 13:01 UTC, matheusfelipeog commented
> hey @Loyoki when are u gonna merge this pr?

Only maintainers can do this. I'll review your PR now ;)

2021-09-02 13:06 UTC, matheusfelipeog requested changes
@thefool76 Can you resolve this review, please?

2021-09-02 13:07 UTC, matheusfelipeog commented
refs:

- Issue #2002
- Original PR: #1916

2021-09-02 13:33 UTC, thefool76 commented on README.md
> +| [Geokeo](https://geokeo.com) | Geokeo geocoding service- with 2500 free api requests daily | No | No | Yes |
@matheusfelipeog Yes sir of course!

2021-09-02 13:39 UTC, thefool76 commented
@matheusfelipeog sorry for the mistake

2021-09-02 13:42 UTC, matheusfelipeog commented
> @matheusfelipeog sorry for the mistake

No problem ;)

2021-09-02 13:43 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for new contribution @thefool76 ;)

2021-09-02 13:45 UTC, merged