added Humor API
public-apis/public-apis pull request #2026
Opened 2021-09-04 21:32 UTC by ddsky

also updated spoonacular API description

- [ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-09-14 21:03 UTC, matheusfelipeog requested changes
Thanks for your contribution @ddsky :)

Can you resolve this review, please?

2021-09-14 21:03 UTC, matheusfelipeog commented on README.md
> +| [Humor API](https://humorapi.com) | Humor, Jokes, and Memes | `apiKey` | Yes | Unknown |
Title should not end with "... API". Every entry is an API here!

```suggestion
| [Humor](https://humorapi.com) | Humor, Jokes, and Memes | `apiKey` | Yes | Unknown |
```

2021-09-16 10:04 UTC, ddsky commented
Thanks for the change, I agree and committed your suggestion :)

2021-09-16 21:24 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for the update @ddsky ;)

2021-09-16 21:26 UTC, merged