added football standings and phone specifications API
public-apis/public-apis pull request #2029
Opened 2021-09-05 02:00 UTC by azharimm

update order football standing API

- [v] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [v] My addition is ordered alphabetically
- [v] My submission has a useful description
- [v] The description does not end with punctuation
- [v] Each table column is padded with one space on either side
- [v] I have searched the repository for any relevant issues or pull requests
- [v] Any category I am creating has the minimum requirement of 3 items
- [v] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-09-05 02:21 UTC, Giahuynh1402 approved these changes

2021-09-14 21:18 UTC, matheusfelipeog requested changes
Thanks for your contribution @azharimm ✋ 

Can you resolve this review, please?

2021-09-14 21:18 UTC, matheusfelipeog commented on README.md
>  | [JCDecaux Bike](https://developer.jcdecaux.com/) | JCDecaux's self-service bicycles | `apiKey` | Yes | Unknown |
Fix the alphabetical order of this API

```suggestion
| [Football Prediction](https://boggio-analytics.com/fp-api/) | Predictions for upcoming football matches, odds, results and stats | `X-Mashape-Key` | Yes | Unknown |
| [Football Standings](https://github.com/azharimm/football-standings-api) | Display football standings e.g epl, la liga, serie a etc. The data is based on espn site | No | Yes | Yes |
| [Football-Data](https://www.football-data.org) | Football data with matches info, players, teams, and competitions | `X-Mashape-Key` | Yes | Unknown |
| [JCDecaux Bike](https://developer.jcdecaux.com/) | JCDecaux's self-service bicycles | `apiKey` | Yes | Unknown |
```

2021-09-14 21:18 UTC, matheusfelipeog commented on README.md
> +
Remove this blank space

```suggestion
```

2021-09-14 22:27 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for the update ;)

2021-09-14 22:28 UTC, merged