Add supportivekoala
public-apis/public-apis pull request #2033
Opened 2021-09-06 20:06 UTC by nadalfederer

- [ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-09-14 21:32 UTC, matheusfelipeog requested changes
Thanks for your contribution @nadalfederer :)

Can you resolve this review, please?

2021-09-14 21:32 UTC, matheusfelipeog commented on README.md
> +| [Supportivekoala](https://developers.supportivekoala.com/) | Autogenerate images with template | apiKey | Yes | Yes |
auth value is not enclosed with \`backticks\`

```suggestion
| [Supportivekoala](https://developers.supportivekoala.com/) | Autogenerate images with template | `apiKey` | Yes | Yes |
```

2021-10-02 21:34 UTC, nadalfederer commented
Hi, I fixed this issue

2021-10-03 04:09 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for your update @nadalfederer ;)

2021-10-03 04:09 UTC, merged