Added a gaming api
public-apis/public-apis pull request #2047
Opened 2021-09-16 09:04 UTC by rahulshawdev

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-09-16 21:45 UTC, matheusfelipeog requested changes
Thanks for your contribution @rahulshawdev 😄 

Can you resolve this review, please?

2021-09-16 21:45 UTC, matheusfelipeog commented on README.md
> +| [RAWG.io](https://rawg.io/apidocs) | 500,000+ games for 50 platforms including mobiles | `apiKey` | Yes | Unknown
You forgot to end the line with |

Fix this:

```suggestion
| [RAWG.io](https://rawg.io/apidocs) | 500,000+ games for 50 platforms including mobiles | `apiKey` | Yes | Unknown |
```

2021-09-17 08:35 UTC, rahulshawdev commented
Done.

2021-09-17 21:39 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for the update @rahulshawdev ;)

2021-09-17 21:39 UTC, merged