added Spanish random names API
public-apis/public-apis pull request #2084
Opened 2021-10-02 06:42 UTC by leahfern

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

NOTE: This is a re-submission of inactive PR #1962 that fulfills the request to clean up the edits to only the API being added. Also made a minor correction to the description. #1962 can now be closed.

2021-10-02 20:21 UTC, matheusfelipeog requested changes
Thanks for your contribution @leahfern 😆 

Can you resolve this review, please?

2021-10-02 20:21 UTC, matheusfelipeog commented on README.md
> +| [Spanish random names](https://random-names-api.herokuapp.com) | Generate spanish names (with gender) randomly | No | Yes | Unknown |
Fix the alphabetical order (before `Spanish random words`) and update to correct link, please:

```suggestion
| [Spanish random names](https://random-names-api.herokuapp.com/public) | Generate spanish names (with gender) randomly | No | Yes | Unknown |
```

2021-10-02 22:39 UTC, leahfern commented
Hi @matheusfelipeog I've updated the PR with your suggestions - thank you!

2021-10-03 00:29 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for your update @leahfern ;)

2021-10-03 00:30 UTC, merged

2021-10-03 00:33 UTC, matheusfelipeog commented
Ref: #2002