Add IMDb API
public-apis/public-apis pull request #2085
Opened 2021-10-02 06:57 UTC by SpEcHiDe

- [ x ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ x ] My addition is ordered alphabetically
- [ x ] My submission has a useful description
- [ x ] The description does not end with punctuation
- [ x ] Each table column is padded with one space on either side
- [ x ] I have searched the repository for any relevant issues or pull requests
- [ x ] Any category I am creating has the minimum requirement of 3 items
- [ x ] All changes have been [squashed][squash-link] into a single commit

2021-10-02 09:50 UTC, kevinunitec commented
I don't want to receive email

2021-10-02 20:40 UTC, matheusfelipeog requested changes
Thanks for your contribution @SpEcHiDe ;)

Can you resolve this review, please?

Also, I tried using this API for testing, but I was unsuccessful. Can you explain how to use it?

2021-10-02 20:40 UTC, matheusfelipeog commented on README.md
> +| [IMDb](https://github.com/SpEcHiDe/IMDbOT) | Unofficial IMDb Movie / Series Information | No | Yes | Yes |
Change the title to IMDbOT, please:

```suggestion
| [IMDbOT](https://github.com/SpEcHiDe/IMDbOT) | Unofficial IMDb Movie / Series Information | No | Yes | Yes |
```

2021-10-03 04:32 UTC, SpEcHiDe commented
Hi, 

you can check the URLs available in the Wiki Pages, 

Example: https://imdbot.vercel.app/?q=avengers%20end%20game


An example repository which is using the api is: https://github.com/SpEcHiDe/Media-Search-bot/blob/master/bot/sessalc/search_imd_b.py#L35

2021-10-03 04:48 UTC, matheusfelipeog commented
> Hi,
> 
> you can check the URLs available in the Wiki Pages,
> 
> Example: https://imdbot.vercel.app/?q=avengers%20end%20game
> 
> An example repository which is using the api is: https://github.com/SpEcHiDe/Media-Search-bot/blob/master/bot/sessalc/search_imd_b.py#L35

Very good. Thanks for showing me

2021-10-03 04:49 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

A big THANKS for your update 😄

2021-10-03 04:49 UTC, merged