Add Lazada
public-apis/public-apis pull request #2114
Opened 2021-10-02 15:35 UTC by cloudy3

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-10-05 06:51 UTC, matheusfelipeog requested changes

2021-10-05 06:51 UTC, matheusfelipeog commented on README.md
> +| [Lazada](https://open.lazada.com/doc/doc.htm?spm=a2o9m.11193487.0.0.3ac413fer0ShaX&nodeId=27493&docId=118729#?nodeId=29586&docId=120248) | Retrieve product ratings and seller performance metrics |
Remove these parameters, they are not necessary.

```suggestion
| [Lazada](https://open.lazada.com/doc/doc.htm) | Retrieve product ratings and seller performance metrics | `apiKey` | Yes | Unknown |
```

2021-10-05 15:46 UTC, cloudy3 commented
Okay resolved!

2021-10-06 02:25 UTC, matheusfelipeog approved these changes
Now it's Ok ✔

Thanks for the update @cloudy3 ;)

2021-10-06 02:26 UTC, merged