Add Breezometer API
public-apis/public-apis pull request #2134
Opened 2021-10-02 20:04 UTC by jayeshchoudhary

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-10-03 11:09 UTC, jayeshchoudhary commented
@pawelborkar can you please review  
this PR is under hactoberfest

2021-10-06 04:38 UTC, matheusfelipeog requested changes
Thanks for your contribution @jayeshchoudhary 😄 

Can you resolve this review, please?

2021-10-06 04:38 UTC, matheusfelipeog commented on README.md
> +| [Breezometer](https://docs.breezometer.com/api-documentation/pollen-api/v2/#daily-forecast) | Daily Forecast pollen conditions data for a specific location | `apiKey` | Yes | Unknown |
- The name of this API is BreezoMeter Pollen
- Remove anchor from link

```suggestion
| [BreezoMeter Pollen](https://docs.breezometer.com/api-documentation/pollen-api/v2/) | Daily Forecast pollen conditions data for a specific location | `apiKey` | Yes | Unknown |
```

2021-10-06 06:32 UTC, jayeshchoudhary commented
done @matheusfelipeog

2021-10-06 06:34 UTC, merged