Update README.md
public-apis/public-apis pull request #2878
Opened 2021-11-01 14:42 UTC by DrNoSleep

- [ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not have more than 100 characters
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-11-01 23:59 UTC, matheusfelipeog requested changes
Thanks for your contribution @DrNoSleep ;)

Can you resolve this review, please?

2021-11-01 23:59 UTC, matheusfelipeog commented on README.md
> +| [owo](https://owo.vc) | A simple link obfuscator/shortener | No | Yes | Unknown |
Change link to: https://owo.vc/api

And fix the alphabetical order, please. 

```suggestion
| [owo](https://owo.vc/api) | A simple link obfuscator/shortener | No | Yes | Unknown |
```

2021-11-02 22:57 UTC, DrNoSleep commented
Should be fixed.

2021-11-02 23:03 UTC, cameron187187 commented
your are the white crayon with stripes soon


Sent from Yahoo Mail for iPhone


On Tuesday, November 2, 2021, 6:01 PM, Seth Carlson ***@***.***> wrote:




Should be fixed.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-11-03 23:38 UTC, matheusfelipeog commented
You must correct the alphabetical order as well @DrNoSleep

2021-11-08 22:00 UTC, DrNoSleep commented
Alright should be sorted alphabetically now.

2021-11-09 17:15 UTC, matheusfelipeog approved these changes
Now it's ok ;)

Thanks for the update @DrNoSleep

2021-11-09 17:15 UTC, merged

2021-11-09 18:37 UTC, DrNoSleep commented
Thank you, and so sorry about the errors 😅