Adding NewsX API to News
public-apis/public-apis pull request #2897
Opened 2021-11-10 02:36 UTC by unixguru2k

- [ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not have more than 100 characters
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-11-10 22:20 UTC, matheusfelipeog requested changes
Thanks for your contribution @unixguru2k ;)

Can you resolve this review, please?

And don't forget to fix the alphabetical order, please

2021-11-10 22:20 UTC, matheusfelipeog commented on README.md
> +| [NewsX by MACHAAO](https://rapidapi.com/machaao-inc-machaao-inc-default/api/newsx/) | Get or Search Latest Breaking News with ML Powered Summaries 🤖 | `apiKey` | Yes | Unknown |
Remove this:  by MACHAAO

```suggestion
| [NewsX](https://rapidapi.com/machaao-inc-machaao-inc-default/api/newsx/) | Get or Search Latest Breaking News with ML Powered Summaries 🤖 | `apiKey` | Yes | Unknown |
```

And don't forget to fix the alphabetical order, please

2021-11-12 18:45 UTC, unixguru2k commented
Thanks for guiding me @matheusfelipeog 
I have updated as per your suggestions.

Cheers
HD

2021-11-24 14:33 UTC, pawelborkar commented
Thanks for the contribution @unixguru2k

2021-11-24 14:33 UTC, merged