Add bet365 API
public-apis/public-apis pull request #2907
Opened 2021-11-18 16:22 UTC by vaishakhp1902

- [✅] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [✅] My addition is ordered alphabetically
- [✅] My submission has a useful description
- [✅] The description does not have more than 100 characters
- [✅] The description does not end with punctuation
- [✅] Each table column is padded with one space on either side
- [✅] I have searched the repository for any relevant issues or pull requests
- [✅] Any category I am creating has the minimum requirement of 3 items
- [✅] All changes have been [squashed][squash-link] into a single commit

2021-11-24 08:02 UTC, pawelborkar requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-11-24 15:28 UTC, pawelborkar requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-11-24 15:28 UTC, pawelborkar commented on README.md
> +| [Bet365](https://rapidapi.com/b365api-b365api-default/api/betsapi2/) | Live results and fixtures on a variety of sports for betting | `apiKey` | Yes | Unknown |
The API is mainly returning the responses related to events. 
So It's better to update the description according to it and please don't use the words like betting and fixture. Please polish the description a bit.

Thanks

2021-11-25 05:57 UTC, pawelborkar commented
Hey @vaishakhp1902,
Can you commit the suggested changes today only?
As we are very close to our milestone.
Please don't forget to squash commits into single one and if you don't know how to do it then you can open a new PR and close this one,

Thanks

2021-11-25 06:15 UTC, vaishakhp1902 commented
Hey @pawelborkar 
Thanks for your reply. I'm pretty new to this, I messed up my branch and was not able to squash, ill close this and open a new one.

Thanks

2021-11-25 06:15 UTC, closed without merging

2021-11-25 07:19 UTC, pawelborkar commented
Sure 😊