Added mcsrvstat.us API
public-apis/public-apis pull request #2950
Opened 2021-12-12 22:04 UTC by antonstech

- [ ] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [ ] My addition is ordered alphabetically
- [ ] My submission has a useful description
- [ ] The description does not have more than 100 characters
- [ ] The description does not end with punctuation
- [ ] Each table column is padded with one space on either side
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Any category I am creating has the minimum requirement of 3 items
- [ ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2021-12-14 02:30 UTC, Jwells560 approved these changes

2021-12-17 06:33 UTC, pawelborkar requested changes
Please commit the suggestions stated below and don't forget to squash all the commits into a single one

2021-12-17 06:33 UTC, pawelborkar commented on README.md
> +| [Minecraft Server Status](https://api.mcsrvstat.us) | API to get Information about a Minecraft Server| No | Yes | No |
```suggestion
| [Minecraft Server Status](https://api.mcsrvstat.us) | API to get Information about a Minecraft Server | No | Yes | No |    
```

2021-12-17 06:33 UTC, pawelborkar commented on README.md
> +| [Minecraft Server Status](https://api.mcsrvstat.us) | API to get Information about a Minecraft Server| No | Yes | No |
each segment must start and end with exactly 1 space

2021-12-18 00:19 UTC, antonstech commented
Sorry, my fault

2021-12-18 16:49 UTC, matheusfelipeog approved these changes
Now it's Ok. ;)

Thanks for the update @antonstech <3

2021-12-18 16:50 UTC, merged