Add Watchdata to Blockchain and Cryptocurrency
public-apis/public-apis pull request #3030
Opened 2022-01-26 11:04 UTC by dsoldatow

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

2022-01-29 00:22 UTC, matheusfelipeog requested changes
Thanks for your contribution @dsoldatow ;)

Can you resolve this review, please?

2022-01-29 00:22 UTC, matheusfelipeog commented on README.md
> +| [Watchdata](https://watchdata.io) | Provide simple and reliable API access to Ethereum blockchain | `apiKey` | Yes | Unknown |
Use the documentation link, please

```suggestion
| [Watchdata](https://docs.watchdata.io) | Provide simple and reliable API access to Ethereum blockchain | `apiKey` | Yes | Unknown |
```

2022-01-29 00:22 UTC, matheusfelipeog commented on README.md
> +| [Watchdata](https://watchdata.io) | Provide simple and reliable API access to Ethereum blockchain | `apiKey` | Yes | Unknown |
And also add this API only in the blockchain category, it is not necessary to add the same API in multiple categories.

```suggestion
```

2022-01-30 16:02 UTC, dsoldatow commented
Thanks, I resolved.

2022-01-31 00:47 UTC, matheusfelipeog approved these changes
Now it's Ok ✅

Thanks for the update @dsoldatow 😄

2022-01-31 00:47 UTC, merged